name: Service 1
on:
   schedule:
     
     - cron: "40 23 * * *" #5:10 AM in IST
     
jobs:
   call-Service1:
     runs-on: ubuntu-latest
     steps:
       - name: trigger api
         run: |
          curl -X GET "https://notify-9fm4.onrender.com/s1" \
          -H "Content-Type: application/json" \
          -H "token:${{secrets.token}}"

       
     
