name: Service 2
on:
    schedule:
     - cron: "20 6 * * *" #11:50 AM in IST
jobs:
    call-Service2:
    runs-on: ubuntu-latest
    steps:
    - name: trigger api
    run: curl -X GET "https://notify-9fm4.onrender.com/s2"