name: Service 2
on:
    schedule:
     - cron: "50 5 * * *" #11:20 AM in IST
jobs:
    call-Service2:
      runs-on: ubuntu-latest
      steps:
       - name: trigger api
         run: |
          curl -X GET "https://notify-9fm4.onrender.com/s2" \
          -H "Content-Type: application/json" \
          -H "token:${{secrets.token}}"